---
title: "WU_LMP"
author: "Jaci Heckman"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(tigerstats)
require(knitr)
require(foreign)
data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)
```

## Regression Model One

```{r}
model1 <- lm(SIMS~ARM, data=data)
plot(SIMS~ARM, data=data)
abline(model1)
summary.lm(model1)
title(main="Plot of SIMS versus ARM")
```


## Predictions

```{r}
new <- data.frame(ARM=88, GRIP=94)
```

```{r}
predict(model1,new,interval="prediction")
```
  
## Regression Model Two

```{r}
model2 <- lm(SIMS~GRIP, data=data)
plot(SIMS~GRIP, data=data)
abline(model2)
summary.lm(model2)
title(main="Plot of SIMS versus GRIP")
```


## Predictions

```{r}
new <- data.frame(ARM=88, GRIP=94)
```

```{r}
predict(model2,new,interval="prediction")
```

## Regression Model Three

```{r}
model3 <- lm(SIMS~ARM+GRIP, data=data)
plot(SIMS~ARM+GRIP, data=data)
abline(model3)
summary.lm(model3)
title(main="Plot of SIMS versus GRIP and ARM")
```

## Predictions

```{r}
new <- data.frame(ARM=88, GRIP=94)
```

```{r}
predict(model3,new,interval="prediction")
```



## Model Comparison Using Anova
  
Comparing Model 1 to Model 3
```{r}
anova(model1, model3)
```
  
Comparing Model 2 to Model 3  
```{r}
anova(model2, model3)
```

Informal Comparison
Comparing model 1 to model 2
```{r}
anova(model1, model2)
```


## Inferential Data

```{r}
model1 <- aov(SIMS~ARM+GRIP,data=data)
summary.aov(model1)
```

## Discussion and Conclusion



